/**
 * Generators for the files blankey scaffolds. Kept as functions rather than
 * static files so they can be written over SSH without shipping assets.
 */

export function traefikCompose(cfg) {
  const t = cfg.traefik;
  const acme = t.acme && t.acme.email;
  const dashboard = t.dashboard && t.dashboardHost;
  const lines: any[] = [];

  lines.push('# Managed by blankey. Edit freely: blankey never overwrites without --force.');
  lines.push('services:');
  lines.push('  traefik:');
  lines.push(`    image: ${t.image}`);
  lines.push('    container_name: traefik');
  lines.push('    restart: unless-stopped');
  lines.push('    security_opt:');
  lines.push('      - no-new-privileges:true');
  lines.push('    ports:');
  lines.push(`      - "${t.entrypoints.web}:80"`);
  lines.push(`      - "${t.entrypoints.websecure}:443"`);
  lines.push('      # API/dashboard bound to loopback only: blankey reads it locally.');
  lines.push('      - "127.0.0.1:8080:8080"');
  lines.push('    volumes:');
  lines.push('      - /var/run/docker.sock:/var/run/docker.sock:ro');
  lines.push('      - ./traefik.yml:/etc/traefik/traefik.yml:ro');
  lines.push('      - ./dynamic:/etc/traefik/dynamic:ro');
  lines.push('      - ./certs:/etc/traefik/certs:ro');
  lines.push('      - ./letsencrypt:/letsencrypt');
  lines.push('      - ./logs:/var/log/traefik');
  lines.push('    networks:');
  lines.push(`      - ${t.network}`);
  lines.push('    labels:');
  lines.push('      - blankey.role=traefik');
  lines.push('      - traefik.enable=true');
  if (dashboard) {
    lines.push(`      - traefik.http.routers.dashboard.rule=Host(\`${t.dashboardHost}\`)`);
    lines.push('      - traefik.http.routers.dashboard.service=api@internal');
    lines.push('      - traefik.http.routers.dashboard.entrypoints=websecure');
    if (acme) lines.push(`      - traefik.http.routers.dashboard.tls.certresolver=${t.acme.resolver}`);
    lines.push('      - traefik.http.routers.dashboard.middlewares=dashboard-auth@file');
  }
  lines.push('');
  lines.push('networks:');
  lines.push(`  ${t.network}:`);
  lines.push('    external: true');
  lines.push('');
  return lines.join('\n');
}

export function traefikStatic(cfg) {
  const t = cfg.traefik;
  const acme = t.acme && t.acme.email;
  const lines: any[] = [];
  lines.push('# Static Traefik configuration, generated by blankey.');
  lines.push('global:');
  lines.push('  checkNewVersion: false');
  lines.push('  sendAnonymousUsage: false');
  lines.push('');
  lines.push('api:');
  lines.push('  dashboard: true');
  lines.push('  # Reachable only on 127.0.0.1:8080 of the Docker host.');
  lines.push('  insecure: true');
  lines.push('');
  lines.push('log:');
  lines.push(`  level: ${t.logLevel}`);
  lines.push('');
  lines.push('accessLog:');
  lines.push('  filePath: /var/log/traefik/access.log');
  lines.push('  bufferingSize: 100');
  lines.push('');
  lines.push('entryPoints:');
  lines.push('  web:');
  lines.push('    address: ":80"');
  if (acme) {
    lines.push('    http:');
    lines.push('      redirections:');
    lines.push('        entryPoint:');
    lines.push('          to: websecure');
    lines.push('          scheme: https');
    lines.push('          permanent: true');
  }
  lines.push('  websecure:');
  lines.push('    address: ":443"');
  lines.push('    http:');
  lines.push('      middlewares:');
  lines.push('        - secure-headers@file');
  if (acme) {
    lines.push('      tls:');
    lines.push(`        certResolver: ${t.acme.resolver}`);
  }
  lines.push('');
  lines.push('providers:');
  lines.push('  docker:');
  lines.push('    endpoint: "unix:///var/run/docker.sock"');
  lines.push('    exposedByDefault: false');
  lines.push(`    network: ${t.network}`);
  lines.push('    watch: true');
  lines.push('  file:');
  lines.push('    directory: /etc/traefik/dynamic');
  lines.push('    watch: true');
  lines.push('');
  if (acme) {
    lines.push('certificatesResolvers:');
    lines.push(`  ${t.acme.resolver}:`);
    lines.push('    acme:');
    lines.push(`      email: ${t.acme.email}`);
    lines.push('      storage: /letsencrypt/acme.json');
    if (t.acme.staging) {
      lines.push('      caServer: https://acme-staging-v02.api.letsencrypt.org/directory');
    }
    lines.push('      httpChallenge:');
    lines.push('        entryPoint: web');
    lines.push('');
  }
  return lines.join('\n');
}

export function traefikDynamic() {
  return [
    '# Dynamic configuration, generated by blankey. Reloaded automatically.',
    'http:',
    '  middlewares:',
    '    secure-headers:',
    '      headers:',
    '        frameDeny: true',
    '        contentTypeNosniff: true',
    '        browserXssFilter: true',
    '        referrerPolicy: strict-origin-when-cross-origin',
    '        stsSeconds: 31536000',
    '        stsIncludeSubdomains: true',
    '',
    '    # Replace the hash below: htpasswd -nb admin yourpassword',
    '    dashboard-auth:',
    '      basicAuth:',
    '        users:',
    '          - "admin:$apr1$changeme$0000000000000000000000"',
    '',
    '    compress:',
    '      compress: {}',
    '',
    '    rate-limit:',
    '      rateLimit:',
    '        average: 100',
    '        burst: 50',
    '',
    'tls:',
    '  options:',
    '    default:',
    '      minVersion: VersionTLS12',
    '      sniStrict: false',
    '',
  ].join('\n');
}

/** The main config file written by `blankey init`. */
export function mainConfig(answers) {
  const l: any[] = [];
  l.push('# blankey configuration');
  l.push('# Docs: every key below is optional except projectsDir.');
  l.push('');
  l.push('# Folder that holds one directory per repo.');
  l.push(`projectsDir: ${answers.projectsDir}`);
  l.push('');
  if (answers.domain) {
    l.push('# Base domain, used for default hostnames and hints.');
    l.push(`domain: ${answers.domain}`);
    l.push('');
  }
  if (answers.sshHost) {
    l.push('# Drive a remote Docker host over SSH instead of the local one.');
    l.push('ssh:');
    l.push(`  host: ${answers.sshHost}`);
    l.push('');
  }
  l.push('traefik:');
  l.push(`  dir: ${answers.traefikDir}`);
  l.push('  # Shared external network every routed container must join.');
  l.push(`  network: ${answers.network}`);
  l.push(`  image: ${answers.image}`);
  l.push(`  dashboard: ${answers.dashboard ? 'true' : 'false'}`);
  if (answers.dashboardHost) l.push(`  dashboardHost: ${answers.dashboardHost}`);
  if (answers.acmeEmail) {
    l.push('  acme:');
    l.push(`    email: ${answers.acmeEmail}`);
    l.push('    resolver: le');
    l.push('    # Flip to true while testing to avoid Let\'s Encrypt rate limits.');
    l.push('    staging: false');
  }
  l.push('');
  l.push('defaults:');
  l.push('  # Stack used when none is named on the command line.');
  l.push('  stack: default');
  l.push('  # ff-only | rebase | reset');
  l.push('  gitStrategy: ff-only');
  l.push('  # Revert to the previous commit when a deploy fails its health check.');
  l.push('  rollbackOnFailure: true');
  l.push('  healthTimeout: 90');
  l.push('  removeOrphans: true');
  l.push('  prune: false');
  l.push('');
  l.push('# Directory names inside projectsDir that are never treated as projects.');
  l.push('ignore:');
  l.push('  - .git');
  l.push('  - node_modules');
  l.push('  - lost+found');
  l.push('');
  l.push('# Per-project overrides, keyed by directory name.');
  l.push('# projects:');
  l.push('#   shop-api:');
  l.push('#     stack: prod');
  l.push('#     alias: shop');
  l.push('');
  return l.join('\n');
}

/** The optional per-repo file, written by `blankey adopt`. */
export function repoConfig(project) {
  const stacks = project.stacks.map((s) => s.name);
  return [
    '# blankey settings for this repo.',
    `# Stacks detected: ${stacks.join(', ')}`,
    '',
    `defaultStack: ${project.defaultStack}`,
    '',
    '# URL blankey polls after a deploy before calling it healthy.',
    '# healthcheck: https://example.com/healthz',
    '',
    '# hooks:',
    '#   preDeploy: ./scripts/pre-deploy.sh',
    '#   postDeploy: ./scripts/post-deploy.sh',
    '',
    '# Pin exactly which files make up a stack, and what to call it in Docker.',
    '# stacks:',
    '#   staging:',
    '#     files: [docker-compose.yml, docker-compose.staging.yml]',
    '#     projectName: myapp-staging',
    '#     env: .env.staging',
    '',
  ].join('\n');
}

/** A ready-to-edit compose file that already plugs into the proxy. */
export function exampleService(cfg, name) {
  const t = cfg.traefik;
  const domainHost = cfg.domain ? `${name}.${cfg.domain}` : `${name}.example.com`;
  const resolver = t.acme && t.acme.email ? `\n      - traefik.http.routers.${name}.tls.certresolver=${t.acme.resolver}` : '';
  return `services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - ${t.network}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${name}.rule=Host(\`${domainHost}\`)
      - traefik.http.routers.${name}.entrypoints=websecure${resolver}
      - traefik.http.services.${name}.loadbalancer.server.port=80

networks:
  ${t.network}:
    external: true
`;
}
